# small script to find the ffmpeg libraries throught pkgconfig

find_package(PkgConfig)
if (PKG_CONFIG_FOUND)
pkg_check_modules(FFMPEG_AVCODEC libavcodec)
pkg_check_modules(FFMPEG_AVFORMAT libavformat)
pkg_check_modules(FFMPEG_AVUTIL libavutil)
pkg_check_modules(FFMPEG_AVDEVICE libavdevice)
pkg_check_modules(FFMPEG_SWSCALE libswscale)
endif (PKG_CONFIG_FOUND)

set(FFMPEG_LIBRARIES
${FFMPEG_AVFORMAT_LIBRARIES} 
${FFMPEG_AVDEVICE_LIBRARIES} 
${FFMPEG_SWSCALE_LIBRARIES}
)

set(FFMPEG_INCLUDE_DIRS
${FFMPEG_AVCODEC_INCLUDE_DIRS} 
)

set(FFMPEG_LIBRARY_DIRS
${FFMPEG_AVCODEC_LIBRARY_DIRS} 
)

if (FFMPEG_SWSCALE_FOUND AND FFMPEG_AVCODEC_FOUND AND FFMPEG_AVFORMAT_FOUND AND FFMPEG_AVUTIL_FOUND AND FFMPEG_AVDEVICE_FOUND)
set(FFMPEG_FOUND TRUE)
endif()

mark_as_advanced(FFMPEG_INCLUDE_DIRS FFMPEG_LIBRARY_DIRS FFMPEG_LIBRARIES FFMPEG_FOUND)

