/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.19
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class jag {
  public final static native String CreateAGSet(String jarg1);
  public final static native boolean ExistsAGSet(String jarg1);
  public final static native void DeleteAGSet(String jarg1);
  public final static native String CreateAG(String jarg1, String jarg2);
  public final static native boolean ExistsAG(String jarg1);
  public final static native void DeleteAG(String jarg1);
  public final static native java.util.Set GetAGIds(String jarg1);
  public final static native String CreateTimeline(String jarg1);
  public final static native boolean ExistsTimeline(String jarg1);
  public final static native void DeleteTimeline(String jarg1);
  public final static native String CreateSignal(String jarg1, String jarg2, String jarg3, String jarg4, String jarg5, String jarg6, String jarg7);
  public final static native boolean ExistsSignal(String jarg1);
  public final static native void DeleteSignal(String jarg1);
  public final static native java.util.Set GetSignals(String jarg1);
  public final static native String GetSignalMimeClass(String jarg1);
  public final static native String GetSignalMimeType(String jarg1);
  public final static native String GetSignalEncoding(String jarg1);
  public final static native String GetSignalXlinkType(String jarg1);
  public final static native String GetSignalXlinkHref(String jarg1);
  public final static native String GetSignalUnit(String jarg1);
  public final static native String GetSignalTrack(String jarg1);
  public final static native String CreateAnnotation(String jarg1, String jarg2, String jarg3, String jarg4);
  public final static native boolean ExistsAnnotation(String jarg1);
  public final static native void DeleteAnnotation(String jarg1);
  public final static native String CopyAnnotation(String jarg1);
  public final static native java.util.List SplitAnnotation(String jarg1);
  public final static native java.util.List NSplitAnnotation(String jarg1, short jarg2);
  public final static native String GetAnnotationType(String jarg1);
  public final static native String GetAnnotationInfo(String jarg1);
  public final static native String GetStartAnchor(String jarg1);
  public final static native String GetEndAnchor(String jarg1);
  public final static native void SetStartAnchor(String jarg1, String jarg2);
  public final static native void SetEndAnchor(String jarg1, String jarg2);
  public final static native double GetStartOffset(String jarg1);
  public final static native double GetEndOffset(String jarg1);
  public final static native void SetStartOffset(String jarg1, double jarg2);
  public final static native void SetEndOffset(String jarg1, double jarg2);
  public final static native java.util.Set GetAnnotationTypes(String jarg1);
  public final static native java.util.Set GetAnnotationFeatureNames__SWIG_0(String jarg1, String jarg2);
  public static java.util.Set GetAnnotationFeatureNames(String jarg1, String jarg2) {
    return GetAnnotationFeatureNames__SWIG_0(jarg1, jarg2);
  }
  public final static native java.util.Set GetAnnotationFeatureNames__SWIG_1(String jarg1);
  public static java.util.Set GetAnnotationFeatureNames(String jarg1) {
    return GetAnnotationFeatureNames__SWIG_1(jarg1);
  }
  public final static native void SetFeature(String jarg1, String jarg2, String jarg3);
  public final static native boolean ExistsFeature(String jarg1, String jarg2);
  public final static native void DeleteFeature(String jarg1, String jarg2);
  public final static native String GetFeature(String jarg1, String jarg2);
  public final static native void UnsetFeature(String jarg1, String jarg2);
  public final static native java.util.Set GetFeatureNames(String jarg1);
  public final static native void SetFeatures(String jarg1, java.util.Map jarg2);
  public final static native java.util.Map GetFeatures(String jarg1);
  public final static native void UnsetFeatures(String jarg1);
  public final static native String CreateAnchor__SWIG_0(String jarg1, double jarg2, String jarg3, java.util.Set jarg4);
  public static String CreateAnchor(String jarg1, double jarg2, String jarg3, java.util.Set jarg4) {
    return CreateAnchor__SWIG_0(jarg1, jarg2, jarg3, jarg4);
  }
  public final static native String CreateAnchor__SWIG_1(String jarg1, java.util.Set jarg2);
  public static String CreateAnchor(String jarg1, java.util.Set jarg2) {
    return CreateAnchor__SWIG_1(jarg1, jarg2);
  }
  public final static native String CreateAnchor__SWIG_2(String jarg1);
  public static String CreateAnchor(String jarg1) {
    return CreateAnchor__SWIG_2(jarg1);
  }
  public final static native boolean ExistsAnchor(String jarg1);
  public final static native void DeleteAnchor(String jarg1);
  public final static native void SetAnchorOffset(String jarg1, double jarg2);
  public final static native double GetAnchorOffset(String jarg1);
  public final static native void SetOffsetUnit(String jarg1, String jarg2);
  public final static native String GetOffsetUnit(String jarg1);
  public final static native void SetAnchorSignalIds(String jarg1, java.util.Set jarg2);
  public final static native java.util.Set GetAnchorSignalIds(String jarg1);
  public final static native boolean GetAnchored(String jarg1);
  public final static native void UnsetAnchorOffset(String jarg1);
  public final static native String SplitAnchor(String jarg1);
  public final static native java.util.Set GetIncomingAnnotationSet__SWIG_0(String jarg1, String jarg2);
  public static java.util.Set GetIncomingAnnotationSet(String jarg1, String jarg2) {
    return GetIncomingAnnotationSet__SWIG_0(jarg1, jarg2);
  }
  public final static native java.util.Set GetIncomingAnnotationSet__SWIG_1(String jarg1);
  public static java.util.Set GetIncomingAnnotationSet(String jarg1) {
    return GetIncomingAnnotationSet__SWIG_1(jarg1);
  }
  public final static native java.util.Set GetOutgoingAnnotationSet__SWIG_0(String jarg1, String jarg2);
  public static java.util.Set GetOutgoingAnnotationSet(String jarg1, String jarg2) {
    return GetOutgoingAnnotationSet__SWIG_0(jarg1, jarg2);
  }
  public final static native java.util.Set GetOutgoingAnnotationSet__SWIG_1(String jarg1);
  public static java.util.Set GetOutgoingAnnotationSet(String jarg1) {
    return GetOutgoingAnnotationSet__SWIG_1(jarg1);
  }
  public final static native java.util.List GetAnchorSet(String jarg1);
  public final static native java.util.List GetAnchorSetByOffset__SWIG_0(String jarg1, double jarg2, double jarg3);
  public static java.util.List GetAnchorSetByOffset(String jarg1, double jarg2, double jarg3) {
    return GetAnchorSetByOffset__SWIG_0(jarg1, jarg2, jarg3);
  }
  public final static native java.util.List GetAnchorSetByOffset__SWIG_1(String jarg1, double jarg2);
  public static java.util.List GetAnchorSetByOffset(String jarg1, double jarg2) {
    return GetAnchorSetByOffset__SWIG_1(jarg1, jarg2);
  }
  public final static native java.util.Set GetAnchorSetNearestOffset(String jarg1, double jarg2);
  public final static native java.util.Set GetAnnotationSet__SWIG_0(String jarg1, String jarg2);
  public static java.util.Set GetAnnotationSet(String jarg1, String jarg2) {
    return GetAnnotationSet__SWIG_0(jarg1, jarg2);
  }
  public final static native java.util.Set GetAnnotationSet__SWIG_1(String jarg1);
  public static java.util.Set GetAnnotationSet(String jarg1) {
    return GetAnnotationSet__SWIG_1(jarg1);
  }
  public final static native java.util.Set GetAnnotationSetByFeature__SWIG_0(String jarg1, String jarg2, String jarg3, String jarg4);
  public static java.util.Set GetAnnotationSetByFeature(String jarg1, String jarg2, String jarg3, String jarg4) {
    return GetAnnotationSetByFeature__SWIG_0(jarg1, jarg2, jarg3, jarg4);
  }
  public final static native java.util.Set GetAnnotationSetByFeature__SWIG_1(String jarg1, String jarg2, String jarg3);
  public static java.util.Set GetAnnotationSetByFeature(String jarg1, String jarg2, String jarg3) {
    return GetAnnotationSetByFeature__SWIG_1(jarg1, jarg2, jarg3);
  }
  public final static native java.util.List GetAnnotationSetByOffset__SWIG_0(String jarg1, double jarg2, String jarg3);
  public static java.util.List GetAnnotationSetByOffset(String jarg1, double jarg2, String jarg3) {
    return GetAnnotationSetByOffset__SWIG_0(jarg1, jarg2, jarg3);
  }
  public final static native java.util.List GetAnnotationSetByOffset__SWIG_1(String jarg1, double jarg2);
  public static java.util.List GetAnnotationSetByOffset(String jarg1, double jarg2) {
    return GetAnnotationSetByOffset__SWIG_1(jarg1, jarg2);
  }
  public final static native java.util.List GetAnnotationSeqByOffset__SWIG_0(String jarg1, double jarg2, double jarg3, String jarg4);
  public static java.util.List GetAnnotationSeqByOffset(String jarg1, double jarg2, double jarg3, String jarg4) {
    return GetAnnotationSeqByOffset__SWIG_0(jarg1, jarg2, jarg3, jarg4);
  }
  public final static native java.util.List GetAnnotationSeqByOffset__SWIG_1(String jarg1, double jarg2, double jarg3);
  public static java.util.List GetAnnotationSeqByOffset(String jarg1, double jarg2, double jarg3) {
    return GetAnnotationSeqByOffset__SWIG_1(jarg1, jarg2, jarg3);
  }
  public final static native java.util.List GetAnnotationSeqByOffset__SWIG_2(String jarg1, double jarg2);
  public static java.util.List GetAnnotationSeqByOffset(String jarg1, double jarg2) {
    return GetAnnotationSeqByOffset__SWIG_2(jarg1, jarg2);
  }
  public final static native java.util.List GetAnnotationSeqByOffset__SWIG_3(String jarg1);
  public static java.util.List GetAnnotationSeqByOffset(String jarg1) {
    return GetAnnotationSeqByOffset__SWIG_3(jarg1);
  }
  public final static native String GetAnnotationByOffset__SWIG_0(String jarg1, double jarg2, String jarg3);
  public static String GetAnnotationByOffset(String jarg1, double jarg2, String jarg3) {
    return GetAnnotationByOffset__SWIG_0(jarg1, jarg2, jarg3);
  }
  public final static native String GetAnnotationByOffset__SWIG_1(String jarg1, double jarg2);
  public static String GetAnnotationByOffset(String jarg1, double jarg2) {
    return GetAnnotationByOffset__SWIG_1(jarg1, jarg2);
  }
  public final static native String GetAGSetId__SWIG_0(String jarg1);
  public static String GetAGSetId(String jarg1) {
    return GetAGSetId__SWIG_0(jarg1);
  }
  public final static native String GetAGSetId__SWIG_1();
  public static String GetAGSetId() {
    return GetAGSetId__SWIG_1();
  }
  public final static native String GetAGId(String jarg1);
  public final static native String GetTimelineId(String jarg1);
  public final static native String toXML(String jarg1);
  public final static native boolean LoadFromDB(String jarg1, String jarg2);
  public final static native boolean StoreToDB(String jarg1, String jarg2);
  public final static native java.util.List StoreSQLs(String jarg1);
  public final static native boolean SPrecedes(String jarg1, String jarg2);
  public final static native java.util.List Load__SWIG_0(String jarg1, String jarg2, String jarg3, java.util.Map jarg4, java.util.Map jarg5);
  public static java.util.List Load(String jarg1, String jarg2, String jarg3, java.util.Map jarg4, java.util.Map jarg5) {
    return Load__SWIG_0(jarg1, jarg2, jarg3, jarg4, jarg5);
  }
  public final static native java.util.List Load__SWIG_1(String jarg1, String jarg2, String jarg3, java.util.Map jarg4);
  public static java.util.List Load(String jarg1, String jarg2, String jarg3, java.util.Map jarg4) {
    return Load__SWIG_1(jarg1, jarg2, jarg3, jarg4);
  }
  public final static native java.util.List Load__SWIG_2(String jarg1, String jarg2, String jarg3);
  public static java.util.List Load(String jarg1, String jarg2, String jarg3) {
    return Load__SWIG_2(jarg1, jarg2, jarg3);
  }
  public final static native java.util.List Load__SWIG_3(String jarg1, String jarg2);
  public static java.util.List Load(String jarg1, String jarg2) {
    return Load__SWIG_3(jarg1, jarg2);
  }
  public final static native String Store__SWIG_0(String jarg1, String jarg2, String jarg3, java.util.Map jarg4);
  public static String Store(String jarg1, String jarg2, String jarg3, java.util.Map jarg4) {
    return Store__SWIG_0(jarg1, jarg2, jarg3, jarg4);
  }
  public final static native String Store__SWIG_1(String jarg1, String jarg2, String jarg3);
  public static String Store(String jarg1, String jarg2, String jarg3) {
    return Store__SWIG_1(jarg1, jarg2, jarg3);
  }
  public final static native String Store2__SWIG_0(String jarg1, String jarg2, java.util.List jarg3, java.util.Map jarg4);
  public static String Store2(String jarg1, String jarg2, java.util.List jarg3, java.util.Map jarg4) {
    return Store2__SWIG_0(jarg1, jarg2, jarg3, jarg4);
  }
  public final static native String Store2__SWIG_1(String jarg1, String jarg2, java.util.List jarg3);
  public static String Store2(String jarg1, String jarg2, java.util.List jarg3) {
    return Store2__SWIG_1(jarg1, jarg2, jarg3);
  }
  public final static native boolean CheckAnchorOffsetTotal(String jarg1, String jarg2);
  public final static native boolean CheckAnchorOffsetBounded(String jarg1, String jarg2);
  public final static native boolean CheckFeatureExists(String jarg1, String jarg2, String jarg3);
  public final static native boolean CheckFeatureIsAnnotationId(String jarg1, String jarg2, String jarg3);
  public final static native boolean CheckLinear(String jarg1, String jarg2);
  public final static native boolean CheckConnected(String jarg1, String jarg2);
  public final static native boolean CheckCoextensive(String jarg1, String jarg2, String jarg3);
  public final static native boolean CheckSpan(String jarg1, String jarg2, String jarg3);
  public final static native String tree_init_tree__SWIG_0(String jarg1, String jarg2);
  public static String tree_init_tree(String jarg1, String jarg2) {
    return tree_init_tree__SWIG_0(jarg1, jarg2);
  }
  public final static native String tree_init_tree__SWIG_1(String jarg1);
  public static String tree_init_tree(String jarg1) {
    return tree_init_tree__SWIG_1(jarg1);
  }
  public final static native boolean tree_move_down__SWIG_0(String jarg1, String jarg2, String jarg3);
  public static boolean tree_move_down(String jarg1, String jarg2, String jarg3) {
    return tree_move_down__SWIG_0(jarg1, jarg2, jarg3);
  }
  public final static native boolean tree_move_down__SWIG_1(String jarg1, String jarg2);
  public static boolean tree_move_down(String jarg1, String jarg2) {
    return tree_move_down__SWIG_1(jarg1, jarg2);
  }
  public final static native boolean tree_move_down__SWIG_2(String jarg1);
  public static boolean tree_move_down(String jarg1) {
    return tree_move_down__SWIG_2(jarg1);
  }
  public final static native boolean tree_move_up(String jarg1);
  public final static native boolean tree_promote_right(String jarg1);
  public final static native boolean tree_promote_left(String jarg1);
  public final static native boolean tree_demote_right(String jarg1);
  public final static native boolean tree_demote_left(String jarg1);
  public final static native String tree_first_tree(String jarg1);
  public final static native String tree_last_tree(String jarg1);
  public final static native boolean tree_move(String jarg1, String jarg2);
  public final static native String tree_insert_node_left__SWIG_0(String jarg1, String jarg2, String jarg3);
  public static String tree_insert_node_left(String jarg1, String jarg2, String jarg3) {
    return tree_insert_node_left__SWIG_0(jarg1, jarg2, jarg3);
  }
  public final static native String tree_insert_node_left__SWIG_1(String jarg1, String jarg2);
  public static String tree_insert_node_left(String jarg1, String jarg2) {
    return tree_insert_node_left__SWIG_1(jarg1, jarg2);
  }
  public final static native String tree_insert_node_left__SWIG_2(String jarg1);
  public static String tree_insert_node_left(String jarg1) {
    return tree_insert_node_left__SWIG_2(jarg1);
  }
  public final static native String tree_insert_node_right__SWIG_0(String jarg1, String jarg2, String jarg3);
  public static String tree_insert_node_right(String jarg1, String jarg2, String jarg3) {
    return tree_insert_node_right__SWIG_0(jarg1, jarg2, jarg3);
  }
  public final static native String tree_insert_node_right__SWIG_1(String jarg1, String jarg2);
  public static String tree_insert_node_right(String jarg1, String jarg2) {
    return tree_insert_node_right__SWIG_1(jarg1, jarg2);
  }
  public final static native String tree_insert_node_right__SWIG_2(String jarg1);
  public static String tree_insert_node_right(String jarg1) {
    return tree_insert_node_right__SWIG_2(jarg1);
  }
  public final static native boolean tree_delete_node_left(String jarg1);
  public final static native boolean tree_delete_node_right(String jarg1);
  public final static native String tree_root__SWIG_0(String jarg1, int jarg2);
  public static String tree_root(String jarg1, int jarg2) {
    return tree_root__SWIG_0(jarg1, jarg2);
  }
  public final static native String tree_root__SWIG_1(String jarg1);
  public static String tree_root(String jarg1) {
    return tree_root__SWIG_1(jarg1);
  }
  public final static native String tree_parent(String jarg1);
  public final static native java.util.List tree_children(String jarg1);
  public final static native String tree_left(String jarg1);
  public final static native String tree_right(String jarg1);
  public final static native java.util.List tree_path(String jarg1);
  public final static native String tree_common_ancestor(String jarg1, String jarg2);
  public final static native String tree_insert_node__SWIG_0(String jarg1, String jarg2, String jarg3, String jarg4);
  public static String tree_insert_node(String jarg1, String jarg2, String jarg3, String jarg4) {
    return tree_insert_node__SWIG_0(jarg1, jarg2, jarg3, jarg4);
  }
  public final static native String tree_insert_node__SWIG_1(String jarg1, String jarg2, String jarg3);
  public static String tree_insert_node(String jarg1, String jarg2, String jarg3) {
    return tree_insert_node__SWIG_1(jarg1, jarg2, jarg3);
  }
  public final static native String tree_insert_node__SWIG_2(String jarg1, String jarg2);
  public static String tree_insert_node(String jarg1, String jarg2) {
    return tree_insert_node__SWIG_2(jarg1, jarg2);
  }
  public final static native boolean tree_delete_node(String jarg1);
}
